---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: cloudnative-dev
  labels:
    app: worker
spec:
  replicas: 2 # Scale this up if the queue gets backed up
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: 483518901689.dkr.ecr.us-east-2.amazonaws.com/cloudnative/worker:latest
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
